name: Deploy Firebase (Functions + Hosting)

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Create functions/.env
        run: |
          mkdir -p functions
          echo "NEIS_API_KEY=${{ secrets.NEIS_API_KEY }}" > functions/.env

      - name: Install Firebase CLI
        run: npm i -g firebase-tools

      - name: Install Functions deps
        run: |
          cd functions
          npm ci

      - name: Deploy to Firebase
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: firebase deploy --only functions,hosting
